Improve networks page
enviodev/docs pull request #400
Opened 2024-08-09 13:32 UTC by moose-code

Small things: 

- Brought banner to top explaining tiers
- Made traces checkmark visible
- Capitalized tier names properly

2024-08-12 09:27 UTC, JonoPrest reviewed
@moose-code I think this doc is auto generated/updated from the script? Can you make sure the script includes the updates you want?

2024-08-12 10:12 UTC, moose-code commented
> @moose-code I think this doc is auto generated/updated from the script? Can you make sure the script includes the updates you want?

Ahh! Good catch, didn't know that. Thanks I should review again then and change the script 🙏

2024-08-12 19:44 UTC, JasoonS requested changes
Yeah, the display isn't affected by this change. Please just check that your change didn't break the auto get (I think it did, because the regex doesn't catch those spaces)

This is the script: https://github.com/enviodev/docs/blob/main/scripts/update-endpoints.js
I think it will match on your change, but the spaces on the other lines won't show. Just verify this (can delete a line such as arbitrum, and it should re-apear after you run `yarn dev`).

2024-08-12 19:46 UTC, JasoonS commented on docs/HyperSync/HyperRPC/hyperrpc-url-endpoints.md
> +
:thinking:

2024-08-12 19:46 UTC, JasoonS commented on docs/HyperSync/HyperRPC/hyperrpc-url-endpoints.md
> +
Is this because of my script?

2024-08-15 09:41 UTC, JasoonS commented on docs/HyperSync/HyperRPC/hyperrpc-url-endpoints.md
> +
Fixed here: https://github.com/enviodev/docs/pull/404

2024-08-15 09:42 UTC, JasoonS approved these changes
Merging

2024-08-15 09:43 UTC, merged