Adds Limitless Prediction Market Blog
enviodev/docs pull request #487
Opened 2024-09-27 13:41 UTC by SvenMuller95

2024-10-01 08:34 UTC, Jordy-Baby approved these changes

2024-10-01 16:31 UTC, moose-code commented on blog/2024-09-27-case-study-limitless.md
> +This new paradigm of prediction markets leverages blockchain technology and cryptocurrency as infrastructure, offering better user experiences than what existed before. Low fees, global accessibility
Last sentence here isn't good! This shouldn't be what blockchain is about, getting around regulations. Its about the transparency and fairness. Lets remove this last sentence

2024-10-01 16:32 UTC, moose-code commented on blog/2024-09-27-case-study-limitless.md
> +Limitless Labs, a new daily prediction market on Base focusing on price action and sporting events, recently hit [$2 million in volume](https://x.com/trylimitless/status/1833621283290157216). A week
suggesting its traction ... is growing?

2024-10-01 16:33 UTC, moose-code requested changes
Great! A couple comments I left to change. You might also want to tag limitless to review this?

2024-10-02 09:02 UTC, moose-code approved these changes
LGTM

2024-10-09 11:53 UTC, Jordy-Baby approved these changes

2024-10-09 11:53 UTC, merged